### ISSUE TITLE
OLED Library in documentation is not correct

### ISSUE THREAD

**Issue by coryjfowler** [angelina-tsuboi/ESP8266-WiCon-Kit#1]
Adding this library to my Arduino IDE solved that compilation issue.  https://github.com/ThingPulse/esp8266-oled-ssd1306

**Comment by ANG13T** [comment]
@coryjfowler I'm glad you got it to work! If possible, can you make a PR with the correct documentation changes? Thank you so much!

**Comment by MoHorst** [comment]
Based on the documentation i run into this issue. It's missing the SH1106Wire.h.
Arduino\WiConKit\WiConKit.ino:29:10: fatal error: SH1106Wire.h: No such file or directory
   29 | #include "SH1106Wire.h"
The library that suggested @coryjfowler could not be compiled.
Which library did you used?

**Comment by ANG13T** [comment]
@coryjfowler what OLED did you use? The OLED library you will have to install depends on the specific OLED type you use. In my case, I used a SH1106 based OLED. 
@MoHorst  you would have to use https://github.com/wonho-maker/Adafruit_SH1106 as listed in the documentation. Thanks!

**Comment by MoHorst** [comment]
I already added this library.
https://github.com/wonho-maker/Adafruit_SH1106  only provide this library.
Adafruit_SH1106.cpp
Adafruit_SH1106.h

You try to load SH1106Wire.h
#include "SH1106Wire.h"

**Comment by coryjfowler** [comment]
@MoHorst Correct, I was getting an error about the #include "SH1106Wire.h" until I tossed the esp8266-oled-ssd1306 library into the appropriate place.   I renamed the library folder name using underscores over hyphens as older Arduino IDE versions had some quirky and strict naming conventions that I am not sure still hold true today, you might try that as I was able to compile until the DNS issue I also posted about.

**Comment by ANG13T** [comment]
Updated README to include https://github.com/ThingPulse/esp8266-oled-ssd1306 library
