### ISSUE TITLE
"WiConKit/WiConKit.ino:361: undefined reference to `dhcps_set_dns'"

### ISSUE THREAD

**Issue by coryjfowler** [angelina-tsuboi/ESP8266-WiCon-Kit#2]
I cannot get past this issue when I try to compile.
The calls to that function are around line 398.
`  // give DNS servers to AP side`
`  dhcps_set_dns(0, WiFi.dnsIP(0));`
`  dhcps_set_dns(1, WiFi.dnsIP(1));`

**Comment by ANG13T** [comment]
Fixed by using the ssd1306 library!

**Comment by coryjfowler** [comment]
What would "dhcp_set_dns()", a very TCP/IP sounding function have to do with the OLED display?  I beg you to reconsider.

**Comment by ANG13T** [comment]
@coryjfowler Whoops. I apologize. I got confused after I read your other issue. The `dhcp_set_dns()` is one of the setup commands for the FTP Honeypot. The FTP Honeypot functionality of this project is derived from this code: [https://github.com/skickar/ESP8266_Router_Honeypot](https://github.com/skickar/ESP8266_Router_Honeypot). Could you follow the steps in the "Requirements" section of that repo and get back to me with the results? Thanks!

**Comment by coryjfowler** [comment]
It appears they have the same issue.  I suspect a library has changed somewhere.  https://github.com/skickar/ESP8266_Router_Honeypot/issues/3

Closing the issue here as I get the issue when compiling their code.
